In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, accuracy_score

In [4]:
df = pd.read_csv('customer_churn_ann_dataset.csv')

In [5]:
df.head()

  CustomerID  Age  TenureMonths  ...  PaperlessBilling  NumSupportTickets Churn
0      C0001   38            20  ...               Yes                  8    No
1      C0002   31             5  ...               Yes                  1    No
2      C0003   32             8  ...               Yes                  4    No
3      C0004   44            19  ...               Yes                  5   Yes
4      C0005   24            71  ...                No                  5   Yes

[5 rows x 12 columns]

In [7]:
df = df.drop(columns=['CustomerID'])

In [8]:
df.head()

   Age  TenureMonths  MonthlyCharges  ...  PaperlessBilling NumSupportTickets Churn
0   38            20              70  ...               Yes                 8    No
1   31             5              31  ...               Yes                 1    No
2   32             8              93  ...               Yes                 4    No
3   44            19              89  ...               Yes                 5   Yes
4   24            71             111  ...                No                 5   Yes

[5 rows x 11 columns]

In [9]:
# Data Cleaning
df['InternetService'] = df['InternetService'].fillna('Unknown')

In [10]:
X_raw = df.drop(columns=['Churn'])

In [11]:
y = df['Churn'].map({'Yes': 1, 'No': 0})